add trello review and images
adhdevops/adhdevops.club pull request #1
Opened 2021-05-01 22:53 UTC by yamikuronue

2021-05-02 18:40 UTC, shelbyspees requested changes
This is fantastic! Thank you for being the first contributor! 💜💜💜

There are a couple copy edits I suggested, plus the front matter thing. Don't stress about the semantic breaks, I can do that myself if I decide I feel strongly enough about it.

You've inspired me to draft a CONTRIBUTING.md 😂

2021-05-02 18:40 UTC, shelbyspees commented on content/posts/review-trello.md
> +tags: [""]
I'm not sure if this theme supports an `author` attribute in the front matter, but I'm planning to change the theme anyway. Go ahead and add an `author` attribute plus an `author_url` one. Probably also good to have `author_pronouns` too.

2021-05-02 18:40 UTC, shelbyspees commented on content/posts/review-trello.md
> +One of the tools [Chloe Condon](https://twitter.com/ChloeCondon) suggested at [Deserted Island DevOps 2021](https://desertedisland.club/) was Trello, currently owned by Atlassian after they bought ou
Nitpicky, but I'm a fan of [semantic line breaks](https://sembr.org/) for version-controlled prose. I won't ask you to change it but it'd be nice to establish that consistency early on.

2021-05-02 18:40 UTC, shelbyspees commented on content/posts/review-trello.md
> +If you're like most of us here at the ADHD Devops Club, you've forgotten a lot of things you meant to get done. Like most of us, you've probably tried post-it notes, but then you lose the post-its! I
```suggestion
If you're like most of us here at the ADHD DevOps Club, you've forgotten a lot of things you meant to get done. Like most of us, you've probably tried post-it notes, but then you lose the post-its! I solved this by making a kanban board out of post-it notes on my crafts room wall.
```

2021-05-02 18:40 UTC, shelbyspees commented on content/posts/review-trello.md
> +![Example kanban board in an office setting. There are four columns: Someday, Soon, Currently, and Recently. Above the board is a quote: "If every pork chop were perfect, we wouldn't have hot dogs."]
Thanks for including image alt-text! 😍 

I'm probably going to move these into sub-directories by date or something so we don't end up with a giant flat directory of image files with vague names and have to grep all over to see where they're used.

2021-05-02 18:40 UTC, shelbyspees commented on content/posts/review-trello.md
> +One of the tools [Chloe Condon](https://twitter.com/ChloeCondon) suggested at [Deserted Island DevOps 2021](https://desertedisland.club/) was Trello, currently owned by Atlassian after they bought ou
Also probably good to link Trello here.

```suggestion
One of the tools [Chloe Condon](https://twitter.com/ChloeCondon) suggested at [Deserted Island DevOps 2021](https://desertedisland.club/) was Trello, currently owned by Atlassian after they bought out the original developers. [Trello](https://trello.com/) is a kanban board, and if you don't know what that is stick with me, because I'm about to explain how it can change your life.
```

2021-05-02 18:40 UTC, shelbyspees commented on content/posts/review-trello.md
> +One of the tools [Chloe Condon](https://twitter.com/ChloeCondon) suggested at [Deserted Island DevOps 2021](https://desertedisland.club/) was Trello, currently owned by Atlassian after they bought ou
(also I'm not sure it's relevant to include the bit about Atlassian but I'll leave that up to you)

2021-05-02 18:40 UTC, shelbyspees commented on content/posts/review-trello.md
> +First of all, I should put many of your mind at ease: the pink background is not standard, this screenshot has been customized. You can put photos or colors as a background to your boards to help dis
```suggestion
First of all, I should put many of your minds at ease: the pink background is not standard, this screenshot has been customized. You can put photos or colors as a background to your boards to help distinguish one from another; the pink is my way of saying this is my personal board, as opposed to my crafting board or my professional board or my writing board. (I have a lot of hobbies!)
```

2021-05-02 18:40 UTC, shelbyspees commented on content/posts/review-trello.md
> +A new board in trello actually begins empty; you are given a curser with a text box at the top of the only column, ready to name it. Naming the column saves it and generates another, and another, unt
```suggestion
A new board in Trello actually begins empty; you are given a curser with a text box at the top of the only column, ready to name it. Naming the column saves it and generates another, and another, until you have the column layout you want. To add a "card" (or to-do item), you click the "add card" button in any column. Out of the box there's no workflow set up; drag and drop the cards where you want them. You can use the software just like that, with no additional features, and get a ton of value out of it.
```

2021-05-02 18:40 UTC, shelbyspees commented on content/posts/review-trello.md
> +tags: [""]
Wait this is yaml, we can nest attributes! I think it would look like this:

```yaml
author:
  name: "Bay Gaillard"
  url: "https://bay.green-gaillard.com"
  pronouns: "they/them"
```

I still need to play around with the theme and templates and things but let's use that for now and play it by ear.

2021-05-02 23:30 UTC, yamikuronue commented on content/posts/review-trello.md
> +One of the tools [Chloe Condon](https://twitter.com/ChloeCondon) suggested at [Deserted Island DevOps 2021](https://desertedisland.club/) was Trello, currently owned by Atlassian after they bought ou
Added semantic line breaks, but I write long sentences so I'm ont sure how much it helps

2021-05-03 01:00 UTC, shelbyspees approved these changes

2021-05-03 01:01 UTC, merged